import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const window={};vm.runInNewContext(fs.readFileSync(new URL('./touchpad.js',import.meta.url),'utf8'),{window,AbortController,performance,setTimeout,clearTimeout});
class Pad extends EventTarget {captures=new Set();setPointerCapture(id){this.captures.add(id);}hasPointerCapture(id){return this.captures.has(id);}releasePointerCapture(id){this.captures.delete(id);}}
function setup(overrides={}){
 const pad=new Pad(),trace=[],timers=new Map();let time=0,id=0,enabled=true;
 const gesture=window.TimDemoTouchpad.mount({element:pad,move:(x,y)=>trace.push(['move',x,y]),tap:()=>trace.push(['tap']),press:()=>{trace.push(['down']);return true;},release:cancelled=>trace.push([cancelled?'cancel-up':'up']),cancel:()=>trace.push(['cancel']),enabled:()=>enabled,now:()=>time,setTimer:(fn,ms)=>{const n=++id;timers.set(n,{fn,when:time+ms});return n;},clearTimer:n=>timers.delete(n),...overrides});
 function advance(ms){const target=time+ms;while(true){const next=[...timers].filter(([,t])=>t.when<=target).sort((a,b)=>a[1].when-b[1].when)[0];if(!next)break;time=next[1].when;timers.delete(next[0]);next[1].fn();}time=target;}
 function event(type,x=50,y=50,extra={}){const e=new Event(type,{cancelable:true});Object.assign(e,{clientX:x,clientY:y,pointerId:1,pointerType:'touch',button:0,buttons:type==='pointerup'?0:1,isPrimary:true,...extra});pad.dispatchEvent(e);return e;}
 return {pad,trace,timers,gesture,advance,event,setEnabled:v=>enabled=v,actions:()=>trace.filter(x=>x[0]!=='move').map(x=>x[0])};
}
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
test('quick tap clicks once without a held press',()=>{const h=setup();h.event('pointerdown');h.advance(80);h.event('pointerup');h.advance(1000);assert.deepEqual(h.actions(),['tap']);assert.equal(h.pad.captures.size,0);});
test('small jitter remains a tap',()=>{const h=setup();h.event('pointerdown');h.event('pointermove',53,52);h.advance(70);h.event('pointerup',53,52);assert.deepEqual(h.actions(),['tap']);});
test('sliding before hold deadline moves pointer without holding or clicking',()=>{const h=setup();h.event('pointerdown');h.event('pointermove',80,50);h.advance(1000);h.event('pointermove',50,50);h.event('pointerup');assert.deepEqual(h.actions(),[]);assert.equal(h.timers.size,0);});
test('350 ms stationary hold sends down before finger lift; no repeat or extra tap',()=>{const h=setup();h.event('pointerdown');h.advance(349);assert.deepEqual(h.actions(),[]);h.advance(1);assert.deepEqual(h.actions(),['down']);h.advance(2000);assert.deepEqual(h.actions(),['down']);h.event('pointerup');assert.deepEqual(h.actions(),['down','up']);});
test('hold then move retains mouse down until lift and includes final coordinates',()=>{const h=setup();h.event('pointerdown');h.advance(400);h.event('pointermove',95,60);h.advance(500);assert.deepEqual(h.actions(),['down']);h.event('pointerup',100,65);assert.deepEqual(h.actions(),['down','up']);assert.deepEqual(h.trace.at(-2),['move',5,5]);});
for(const type of ['pointercancel','lostpointercapture'])for(const held of [false,true])test(type+' '+(held?'held':'pending')+' does not click or leave a timer/button down',()=>{const h=setup();h.event('pointerdown');h.advance(held?400:80);h.event(type);h.event('pointerup');h.advance(1000);assert.deepEqual(h.actions(),held?['down','cancel-up','cancel']:['cancel']);assert.equal(h.timers.size,0);assert.equal(h.pad.captures.size,0);});
test('second finger cannot steal, release or restart first hold',()=>{const h=setup();h.event('pointerdown');h.event('pointerdown',90,90,{pointerId:2,isPrimary:false});h.advance(400);h.event('pointerup',90,90,{pointerId:2,isPrimary:false});assert.deepEqual(h.actions(),['down']);h.event('pointerup');assert.deepEqual(h.actions(),['down','up']);});
test('secondary-only and non-left clicks are ignored',()=>{const h=setup();h.event('pointerdown',50,50,{isPrimary:false});h.advance(500);h.event('pointerup');h.event('pointerdown',50,50,{button:2});h.advance(500);assert.deepEqual(h.actions(),[]);});
test('disabled touchpad cannot start a press',()=>{const h=setup();h.setEnabled(false);h.event('pointerdown');h.advance(500);h.event('pointerup');assert.deepEqual(h.actions(),[]);});
test('loss of enabled state releases on next event',()=>{const h=setup();h.event('pointerdown');h.advance(400);h.setEnabled(false);h.event('pointermove');assert.deepEqual(h.actions(),['down','cancel-up','cancel']);});
test('explicit cancel is idempotent and clears a pending timer',()=>{const h=setup();h.event('pointerdown');h.gesture.cancel();h.gesture.cancel();h.advance(500);h.event('pointerup');assert.deepEqual(h.actions(),['cancel']);});
test('mouse loss of physical button cancels a held state',()=>{const h=setup();h.event('pointerdown',50,50,{pointerType:'mouse'});h.advance(400);h.event('pointermove',60,50,{pointerType:'mouse',buttons:0});assert.deepEqual(h.actions(),['down','cancel-up','cancel']);});
for(const held of [false,true])test('destroy cleans '+(held?'held':'pending')+' gesture and listeners',()=>{const h=setup();h.event('pointerdown');h.advance(held?400:80);h.gesture.destroy();h.advance(1000);h.event('pointerdown');h.advance(500);h.event('pointerup');assert.deepEqual(h.actions(),held?['down','cancel-up','cancel']:['cancel']);assert.equal(h.timers.size,0);});
test('refused press owns no button and does not release another hold',()=>{const h=setup({press:()=>false});h.event('pointerdown');h.advance(500);h.event('pointerup');assert.deepEqual(h.actions(),[]);});
test('native context menu suppressed only on the game touchpad',()=>{const h=setup();assert.equal(h.event('contextmenu').defaultPrevented,true);});
console.log(`PASS ${count} deterministic touch gesture scenarios.`);