/* Browser-native accessories. No commands are executed on the visitor's computer. */
(() => {
  'use strict';
  const apps=new Map(), W=window.TimWindows;
  const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}};
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function register(id,label,icon,mount){apps.set(id,{id,label,icon,mount});}
  function open(id){const app=apps.get(id);if(!app)return false;let cleanup=()=>{},visibility=()=>{};
    const panel=W.openPanel({id,title:app.label,label:app.label,icon:app.icon,html:'',onClose:()=>cleanup(),onVisibility:v=>visibility(v)});
    if(panel.created){panel.el.classList.add('classic-app');panel.el.dataset.app=id;const cleanBody=panel.body.cloneNode(false);panel.body.replaceWith(cleanBody);const result=app.mount(cleanBody,panel.el)||{};cleanup=result.cleanup||cleanup;visibility=result.visibility||visibility;}
    document.querySelector('#start-menu').hidden=true;document.querySelector('#start-button').setAttribute('aria-expanded','false');return true;
  }
  const button=(label,action)=>`<button class="bevel-button" data-command="${action}">${label}</button>`;
  window.TimApps=Object.freeze({register,open,safe,read,save,download,button,list:()=>[...apps.values()].map(({id,label,icon})=>({id,label,icon}))});
  document.addEventListener('click',e=>{const app=e.target.closest('[data-app-open]');if(app){e.preventDefault();open(app.dataset.appOpen);}});
  register('datetime','Date/Time Properties','clock',(body)=>{
    let today=new Date(),year=today.getFullYear(),month=today.getMonth(),selected=today.getDate(),timer;
    body.innerHTML='<div class="accessory-pad"><div class="classic-tabs"><button class="selected">Date &amp; Time</button></div><div class="date-layout"><section><div class="calendar-nav"><button data-month="-1" aria-label="Previous month">◀</button><strong id="calendar-month"></strong><button data-month="1" aria-label="Next month">▶</button></div><div id="calendar-grid" class="calendar-grid" role="grid" aria-label="Calendar"></div><button class="bevel-button" id="calendar-today">Today</button></section><section class="clock-section"><div class="analog-clock" aria-hidden="true"><span class="clock-12">12</span><span class="clock-3">3</span><span class="clock-6">6</span><span class="clock-9">9</span><i class="clock-hand hours"></i><i class="clock-hand minutes"></i><i class="clock-hand seconds"></i><b></b></div><time id="live-time"></time><p id="clock-zone"></p></section></div><p class="accessory-note">Shows your device’s local time. Browsing the calendar does not change your computer’s date or time.</p></div>';
    const q=s=>body.querySelector(s);
    function calendar(){q('#calendar-month').textContent=new Date(year,month,1).toLocaleDateString([],{month:'long',year:'numeric'});const grid=q('#calendar-grid');grid.replaceChildren();for(const day of ['Su','Mo','Tu','We','Th','Fr','Sa']){const b=document.createElement('span');b.className='weekday';b.textContent=day;grid.append(b);}const start=new Date(year,month,1).getDay(),count=new Date(year,month+1,0).getDate();for(let i=0;i<start;i++)grid.append(document.createElement('span'));for(let d=1;d<=count;d++){const b=document.createElement('button');b.textContent=d;b.dataset.day=d;b.setAttribute('role','gridcell');b.setAttribute('aria-selected',String(d===selected));b.setAttribute('aria-label',new Date(year,month,d).toLocaleDateString([],{dateStyle:'full'}));if(d===today.getDate()&&month===today.getMonth()&&year===today.getFullYear())b.className='today';grid.append(b);}}
    function tick(){const n=new Date();q('#live-time').textContent=n.toLocaleTimeString();q('#clock-zone').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone;q('.hours').style.transform=`rotate(${n.getHours()%12*30+n.getMinutes()/2}deg)`;q('.minutes').style.transform=`rotate(${n.getMinutes()*6+n.getSeconds()/10}deg)`;q('.seconds').style.transform=`rotate(${n.getSeconds()*6}deg)`;if(n.toDateString()!==today.toDateString()){today=n;calendar();}}
    body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.month){const d=new Date(year,month+Number(b.dataset.month),1);year=d.getFullYear();month=d.getMonth();selected=0;calendar();}else if(b.dataset.day){selected=Number(b.dataset.day);calendar();}else if(b.id==='calendar-today'){today=new Date();year=today.getFullYear();month=today.getMonth();selected=today.getDate();calendar();}});
    calendar();tick();timer=setInterval(tick,1000);return {cleanup:()=>clearInterval(timer),visibility:v=>{clearInterval(timer);if(v){tick();timer=setInterval(tick,1000);}}};
  });
  register('calculator','Calculator','calculator',(body)=>{
    const model=new window.TimClassicEngines.Calculator();
    const keys=[['MC','MC'],['MR','MR'],['MS','MS'],['M+','M+'],['BS','Back'],['CE','CE'],['C','C'],['sqrt','√'],['7','7'],['8','8'],['9','9'],['/','÷'],['4','4'],['5','5'],['6','6'],['*','×'],['1','1'],['2','2'],['3','3'],['-','−'],['0','0'],['.','.'],['+/-','±'],['+','+'],['1/x','1/x'],['%','%'],['=','=']];
    body.innerHTML='<div class="calculator-app"><div class="app-menubar">Standard</div><output id="calculator-display" aria-live="polite">0</output><span id="calculator-memory" class="accessory-note">Memory empty</span><div class="calculator-keys">'+keys.map(([key,label])=>`<button class="bevel-button ${key==='='?'calc-equals':''}" data-calc="${key}">${label}</button>`).join('')+'</div></div>';
    const input=key=>{model.input(key);body.querySelector('#calculator-display').textContent=model.display;body.querySelector('#calculator-memory').textContent=model.memory?'M':'Memory empty';};
    body.addEventListener('click',e=>{const b=e.target.closest('[data-calc]');if(b)input(b.dataset.calc);});
    body.closest('.app-window').onkeydown=e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const key=/^[0-9.+*/%=-]$/.test(e.key)?e.key:({Enter:'=',Backspace:'BS',Delete:'CE',Escape:'C'})[e.key];if(key){e.preventDefault();e.stopPropagation();input(key);}};
    return {cleanup:()=>{body.closest('.app-window').onkeydown=null;}};
  });
  register('notepad','Notepad','notepad',(body,el)=>{
    const key='timbuilds.notepad.v1',trashKey='timbuilds.recycle.v1';let text=read(key,''),wrap=true;
    if(typeof text!=='string')text='';body.innerHTML='<div class="notepad-app"><div class="app-menubar">'+button('New','new')+button('Open…','open')+button('Save .txt','save')+button('Select all','select')+button('Word wrap','wrap')+button('Recycle note','recycle')+'</div><input type="file" accept="text/plain,.txt,.md,.log" hidden id="note-file"><textarea id="notepad-text" aria-label="Notepad document" spellcheck="false" maxlength="1000000"></textarea><div class="note-status" role="status"></div></div>';
    const area=body.querySelector('textarea'),status=body.querySelector('.note-status');area.value=text;
    function update(){text=area.value;const ok=save(key,text);status.textContent=(ok?'Saved in this browser':'Storage unavailable; save a .txt copy')+' · '+text.length+' characters';}
    function recycle(){if(!area.value)return;const trash=read(trashKey,[]);if(!Array.isArray(trash))return;const next=[{id:Date.now().toString(36),title:'Notepad — '+new Date().toLocaleString(),text:area.value},...trash].slice(0,10);if(!save(trashKey,next)){status.textContent='Recycle Bin could not save the note. Your text was kept.';return;}area.value='';update();window.dispatchEvent(new Event('timbuilds-files'));}
    area.addEventListener('input',update);body.addEventListener('click',e=>{const c=e.target.closest('[data-command]')?.dataset.command;if(c==='save')download(new Blob([area.value],{type:'text/plain;charset=utf-8'}),'Untitled.txt');if(c==='open')body.querySelector('#note-file').click();if(c==='new'||c==='recycle')recycle();if(c==='select'){area.focus();area.select();}if(c==='wrap'){wrap=!wrap;area.wrap=wrap?'soft':'off';e.target.setAttribute('aria-pressed',String(wrap));}});
    body.querySelector('#note-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>1000000){status.textContent='Choose a text file smaller than 1 MB.';return;}const incoming=await f.text();if(!el.isConnected||el.hidden)return;if(area.value){recycle();if(area.value)return;}area.value=incoming;update();e.target.value='';});
    area.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();download(new Blob([area.value],{type:'text/plain;charset=utf-8'}),'Untitled.txt');}});update();area.focus({preventScroll:true});
  });
  register('recycle','Recycle Bin','recycle',(body)=>{
    const key='timbuilds.recycle.v1';let confirmEmpty=false;
    function render(){const items=read(key,[]);body.innerHTML='<div class="accessory-pad"><p>Deleted browser notes. Nothing on your actual computer is touched.</p><div class="recycle-items">'+(Array.isArray(items)&&items.length?items.map(x=>`<div class="recycle-item"><span>${safe(x.title)}</span><button class="bevel-button" data-restore="${safe(x.id)}">Restore</button><button class="bevel-button" data-export="${safe(x.id)}">Save .txt</button></div>`).join(''):'<p>The Recycle Bin is empty.</p>')+'</div><button class="bevel-button" data-empty>'+ (confirmEmpty?'Confirm permanently empty browser notes':'Empty Recycle Bin')+'</button><p class="accessory-note">Restore replaces an empty Notepad. When Notepad contains text, the restored copy downloads instead.</p></div>';}
    body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const items=read(key,[]);if(!Array.isArray(items))return;const id=b.dataset.restore||b.dataset.export,item=items.find(i=>i.id===id);if(item){if(b.dataset.export||read('timbuilds.notepad.v1',''))download(new Blob([item.text],{type:'text/plain'}),'Restored-note.txt');else{if(!save('timbuilds.notepad.v1',item.text))return;W.close('notepad');open('notepad');}if(b.dataset.restore){save(key,items.filter(i=>i.id!==id));render();}}if(b.hasAttribute('data-empty')){if(confirmEmpty){save(key,[]);confirmEmpty=false;}else confirmEmpty=true;render();}});render();const refresh=()=>render();window.addEventListener('timbuilds-files',refresh);return {cleanup:()=>window.removeEventListener('timbuilds-files',refresh)};
  });
})();
