/* The game cannot grant access. Only possession of the private catalogue key can. */
(() => {
  'use strict';
  window.addEventListener('hashchange',()=>{if(new URLSearchParams(location.hash.slice(1)).has('owner-key'))location.reload();});
  let enrollment=new URLSearchParams(location.hash.slice(1)).get('owner-key');
  // Remove the capability from the current history entry before async work or navigation.
  if(enrollment){try{history.replaceState(null,'',location.pathname+location.search);}catch{enrollment=null;}}
  const decode=value=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
  function store(mode,key){return new Promise((resolve,reject)=>{const req=indexedDB.open('timbuilds-owner-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('keys');req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('Storage unavailable'));req.onsuccess=()=>{const db=req.result;let value;const tx=db.transaction('keys',mode);const op=mode==='readwrite'?tx.objectStore('keys').put(key,'catalogue'):tx.objectStore('keys').get('catalogue');op.onsuccess=()=>{value=op.result;};tx.oncomplete=()=>{db.close();resolve(value);};tx.onabort=tx.onerror=()=>{db.close();reject(tx.error||new Error('Storage unavailable'));};};});}
  async function decrypt(key){const response=await fetch('portfolio/locked.json',{cache:'no-store',credentials:'omit'});if(!response.ok)throw new Error('Catalogue unavailable');const payload=await response.json();if(payload.v!==1)throw new Error('Unsupported catalogue');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(payload.iv),additionalData:new TextEncoder().encode('timbuilds.locked.v1')},key,decode(payload.ciphertext));const projects=JSON.parse(new TextDecoder().decode(plain));if(!Array.isArray(projects)||projects.length>100)throw new Error('Invalid catalogue');const ids=new Set();for(const p of projects){if(!/^[a-z0-9-]+$/.test(p.id)||ids.has(p.id)||!Array.isArray(p.stack)||!p.stack.every(v=>typeof v==='string')||!['title','summary','detail','category','status','icon','preview'].every(k=>typeof p[k]==='string')||!['icon','preview'].every(k=>/^[a-z0-9-]+$/.test(p[k]))||p.url&&(!p.url.startsWith('https://')&&p.url!=='/openhoops/'))throw new Error('Invalid catalogue');ids.add(p.id);}return projects;}
  const ready=(async()=>{const enrolling=Boolean(enrollment);try{if(!crypto.subtle)throw new Error('Secure browser required');let key;if(enrollment){if(!/^[A-Za-z0-9_-]{43}$/.test(enrollment))throw new Error('Invalid capability');const bytes=decode(enrollment);enrollment=null;key=await crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['decrypt']);bytes.fill(0);}else{try{key=await store('readonly');}catch{return {projects:null};}}if(!key)return {projects:null};const projects=await decrypt(key);let persistent=true;if(enrolling){try{await store('readwrite',key);}catch{persistent=false;}}return {projects,enrolled:enrolling,persistent};}catch{enrollment=null;return {projects:null,enrollmentFailed:enrolling};}})();
  const hints=[
    'Hint 1: Tim probably used something memorable. Unfortunately, memory is not admissible evidence.',
    'Hint 2: Try at least eight characters. A committee has classified spaces as furniture.',
    'Hint 3: There is a number in it. Its identity is protected under witness protection.',
    'Hint 4: Include a capital. Not a capital letter. A national capital, circa 1995.',
    'Hint 5: The password contains the sound a floppy disk makes when it is disappointed.',
    'Hint 6: Exactly one character is lying. All the others have retained counsel.',
    'Hint 7: It must be longer than your previous guess, but take less time to pronounce.',
    'Hint 8: Use a prime number of characters. The prime must also be divisible by twelve.',
    'Hint 9: Include yesterday’s weather on a planet that has not been discovered.',
    'Hint 10: We need twelve letters. Letters are now prohibited. Please comply with both rules.',
    'Hint 11: Your guess requires a reference from a password that has known it for five years.',
    'Hint 12: Please enter the exact shade of beige of Tim’s imaginary childhood computer.',
    'Hint 13: Include a silent emoji. It must be audible to the reviewer.',
    'Hint 14: The correct password is case-sensitive, mood-sensitive and slightly disappointed.',
    'Hint 15: Obtain approval from the Department of Previously Incorrect Guesses.',
    'Hint 16: Your password was correct in a parallel universe. That universe is closed on Thursdays.'
  ];
  let round=0;
  try{round=Math.min(10000,Math.max(0,Number(sessionStorage.getItem('timbuilds.guessing-round'))||0));}catch{}
  const choices=[['password123','Tim’s favourite floppy disk','The name of a very reliable goose'],['Ottawa1995','Eight suspicious spaces','A strongly worded apology'],['A silent emoji','Twelve prime letters','The colour of dial-up'],['Yesterday on Neptune','A notarised shrug','The administrator’s imaginary cat']];
  function hint(n){return hints[n]||`Hint ${n+1}: Submit ${Math.min(n,9999)} notarised copies of your previous guess, translated into the future tense of a language that has no future.`;}
  function renderGame(){return '<div class="project-detail-copy password-game"><div class="eyebrow">ACCESS DENIED · THE GUESSING DEPARTMENT</div><h2>Surely one of these will work.</h2><p>A fictional password puzzle. Pick a made-up guess. Our hint department will make things substantially less helpful.</p><p class="game-safety">Just a game—not a sign-in. No credentials are requested or collected.</p><div class="game-stats"><span>Attempts <strong id="guess-count"></strong></span><span>Difficulty <strong id="guess-difficulty"></strong></span><span>Staff on duty <strong>0</strong></span></div><div id="guess-choices" class="guess-choices" aria-label="Fictional guesses"></div><p id="guess-feedback" class="guess-feedback" role="status" aria-live="polite">Pick your most convincing guess.</p><ol class="guess-hints" id="guess-hints" reversed></ol><div class="detail-actions"><button class="bevel-button" data-action="guess-hint">Request an unhelpful hint</button><button class="text-button" data-action="guess-reset">Restart the paperwork</button><button class="text-button" data-action="close-dialog">Abandon application</button></div></div>';}
  function paintGame(){const choiceBox=document.querySelector('#guess-choices');if(!choiceBox)return;document.querySelector('#guess-count').textContent=String(round);document.querySelector('#guess-difficulty').textContent=`2^${round}`;choiceBox.replaceChildren();for(const [i,text] of choices[Math.min(Math.floor(round/4),choices.length-1)].entries()){const button=document.createElement('button');button.className='bevel-button';button.dataset.guessChoice=String(i);button.textContent=text;choiceBox.appendChild(button);}const list=document.querySelector('#guess-hints');list.replaceChildren();list.start=round+1;for(let n=round;n>=Math.max(0,round-5);n--){const li=document.createElement('li');li.textContent=hint(n);list.appendChild(li);}}
  function advance(){round=Math.min(round+1,10000);try{sessionStorage.setItem('timbuilds.guessing-round',String(round));}catch{}paintGame();document.querySelector('#guess-feedback').textContent=['Incorrect. A new requirement has arrived.','Access denied. Your guess has been forwarded to a smaller committee.','Still incorrect. We doubled the difficulty for your convenience.','Nearly! By which we mean not at all.','Your appeal was denied by a fax machine.'][round%5];document.querySelector('#guess-choices button').focus({preventScroll:true});}
  document.addEventListener('click',event=>{if(!document.querySelector('#guess-choices'))return;const button=event.target.closest('button');if(!button)return;if(button.dataset.guessChoice!==undefined||button.dataset.action==='guess-hint')advance();if(button.dataset.action==='guess-reset'){round=0;try{sessionStorage.removeItem('timbuilds.guessing-round');}catch{}paintGame();document.querySelector('#guess-feedback').textContent='A fresh form. The same unhelpful department.';}});
  window.TimLocked=Object.freeze({ready,renderGame,paintGame});
})();
