/* The game cannot grant access. Only possession of the private catalogue key can. */
(() => {
  'use strict';
  window.addEventListener('hashchange',()=>{if(new URLSearchParams(location.hash.slice(1)).has('owner-key'))location.reload();});
  let enrollment=new URLSearchParams(location.hash.slice(1)).get('owner-key');
  // Remove the capability from the current history entry before async work or navigation.
  if(enrollment){try{history.replaceState(null,'',location.pathname+location.search);}catch{enrollment=null;}}
  const decode=value=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
  function store(mode,key){return new Promise((resolve,reject)=>{const req=indexedDB.open('timbuilds-owner-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('keys');req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('Storage unavailable'));req.onsuccess=()=>{const db=req.result;let value;const tx=db.transaction('keys',mode);const op=mode==='readwrite'?tx.objectStore('keys').put(key,'catalogue'):tx.objectStore('keys').get('catalogue');op.onsuccess=()=>{value=op.result;};tx.oncomplete=()=>{db.close();resolve(value);};tx.onabort=tx.onerror=()=>{db.close();reject(tx.error||new Error('Storage unavailable'));};};});}
  async function decrypt(key){const response=await fetch('portfolio/locked.json',{cache:'no-store',credentials:'omit'});if(!response.ok)throw new Error('Catalogue unavailable');const payload=await response.json();if(payload.v!==1)throw new Error('Unsupported catalogue');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(payload.iv),additionalData:new TextEncoder().encode('timbuilds.locked.v1')},key,decode(payload.ciphertext));const projects=JSON.parse(new TextDecoder().decode(plain));if(!Array.isArray(projects)||projects.length>100)throw new Error('Invalid catalogue');const ids=new Set();for(const p of projects){if(!/^[a-z0-9-]+$/.test(p.id)||ids.has(p.id)||!Array.isArray(p.stack)||!p.stack.every(v=>typeof v==='string')||!['title','summary','detail','category','status','icon','preview'].every(k=>typeof p[k]==='string')||!['icon','preview'].every(k=>/^[a-z0-9-]+$/.test(p[k]))||p.url&&(!p.url.startsWith('https://')&&p.url!=='/openhoops/'))throw new Error('Invalid catalogue');ids.add(p.id);}return projects;}
  const ready=(async()=>{const enrolling=Boolean(enrollment);try{if(!crypto.subtle)throw new Error('Secure browser required');let key;if(enrollment){if(!/^[A-Za-z0-9_-]{43}$/.test(enrollment))throw new Error('Invalid capability');const bytes=decode(enrollment);enrollment=null;key=await crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['decrypt']);bytes.fill(0);}else{try{key=await store('readonly');}catch{return {projects:null};}}if(!key)return {projects:null};const projects=await decrypt(key);let persistent=true;if(enrolling){try{await store('readwrite',key);}catch{persistent=false;}}return {projects,enrolled:enrolling,persistent};}catch{enrollment=null;return {projects:null,enrollmentFailed:enrolling};}})();
  window.TimLocked=Object.freeze({ready});
})();
