/* Self-hosted Open Cadet wrapper: starts on demand, stops when closed. */
(() => {
  'use strict';
  window.TimApps.register('pinball','Pinball','pinball',(body,el)=>{
    let ready=false,visible=true,paused=false,muted=true,closed=false;
    body.innerHTML='<div class="pinball-app"><div class="app-menubar"><button class="bevel-button" data-pin-action="new">New game</button><button class="bevel-button" data-pin-action="pause" aria-pressed="false">Pause</button><button class="bevel-button" data-pin-action="sound" aria-pressed="false">Sound off</button></div><iframe id="pinball-frame" title="Space Cadet pinball with Open Cadet artwork" src="portfolio/vendor/pinball/index.html?v=6" sandbox="allow-scripts allow-same-origin" allow="autoplay"></iframe><div class="pinball-touch"><button data-pin-key="left">Left flipper · Z</button><button data-pin-key="launch">Hold to launch · Space</button><button data-pin-key="right">Right flipper · /</button></div><p class="accessory-note" id="pinball-status" role="status">Loading the table…</p><p class="accessory-note">Space Cadet engine · Open Cadet replacement artwork and sounds. <a href="portfolio/vendor/pinball/OPEN-CADET-NOTICE.md" target="_blank" rel="noopener">Credits</a></p></div>';
    const frame=body.querySelector('iframe'),status=body.querySelector('#pinball-status');
    const send=(action,value)=>{if(!closed)frame.contentWindow?.postMessage({type:'timbuilds-pinball',action,...value},location.origin);};
    const resume=()=>send('visibility',{value:visible&&!paused&&!document.hidden});
    function key(name,down){send('key',{key:name,down});}
    const onMessage=e=>{if(e.source!==frame.contentWindow||e.origin!==location.origin||!['timbuilds-pinball-ready','timbuilds-pinball-error'].includes(e.data?.type))return;if(e.data.type==='timbuilds-pinball-error'){status.textContent='Pinball needs WebGL graphics in this browser. The other accessories do not.';el.dataset.pinballReady='unsupported';return;}ready=true;el.dataset.pinballReady='true';status.textContent='Press New game, then hold and release Space to launch. Z and / control the flippers.';send('mute',{value:muted});resume();};
    window.addEventListener('message',onMessage);
    body.addEventListener('click',e=>{const b=e.target.closest('[data-pin-action]');if(!b)return;const action=b.dataset.pinAction;if(action==='new'){if(!ready){if(el.dataset.pinballReady!=='unsupported')status.textContent='The table is still loading.';return;}paused=false;body.querySelector('[data-pin-action="pause"]').textContent='Pause';resume();key('new',true);setTimeout(()=>key('new',false),70);status.textContent='Hold and release Space to launch. Z and / control the flippers.';}else if(action==='pause'){paused=!paused;b.textContent=paused?'Resume':'Pause';b.setAttribute('aria-pressed',String(paused));resume();}else if(action==='sound'){muted=!muted;b.textContent=muted?'Sound off':'Sound on';b.setAttribute('aria-pressed',String(!muted));send('mute',{value:muted});}});
    for(const b of body.querySelectorAll('[data-pin-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);key(b.dataset.pinKey,true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>key(b.dataset.pinKey,false));b.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();if(!e.repeat)key(b.dataset.pinKey,true);}});b.addEventListener('keyup',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();key(b.dataset.pinKey,false);}});}
    const onVisible=()=>resume();document.addEventListener('visibilitychange',onVisible);
    const timeout=setTimeout(()=>{if(!ready&&!closed&&el.dataset.pinballReady!=='unsupported')status.textContent='The table is taking longer to load. Close and reopen Pinball to retry.';},30000);
    return {cleanup:()=>{closed=true;clearTimeout(timeout);window.removeEventListener('message',onMessage);document.removeEventListener('visibilitychange',onVisible);frame.src='about:blank';frame.remove();},visibility:v=>{visible=v;resume();}};
  });
})();
