/* OS-inspired power sequences; no operating-system commands or browser-limit bypasses. */
(() => {
  'use strict';
  const A=window.TimApps,W=window.TimWindows,V=window.TimVersion;let screen=null,timers=[],generation=0,previousInert=[],mode='off';
  const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
  function clearTimers(){timers.forEach(clearTimeout);timers=[];generation++;}
  function later(fn,ms){const g=generation;timers.push(setTimeout(()=>{if(g===generation)fn();},ms));}
  function removeScreen(){clearTimers();screen?.remove();screen=null;for(const [el,value] of previousInert)el.inert=value;previousInert=[];document.querySelector('.desktop-shortcut')?.focus({preventScroll:true});}
  function createScreen(){if(screen)return;previousInert=[...document.body.children].map(el=>[el,el.inert]);for(const [el] of previousInert)el.inert=true;screen=document.createElement('section');screen.className='desktop-cover power-screen';screen.dataset.powerOs=V.current();screen.setAttribute('role','dialog');screen.setAttribute('aria-modal','true');screen.setAttribute('aria-label',V.info().name+' power sequence');screen.tabIndex=-1;document.body.append(screen);screen.focus();screen.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(screen.dataset.phase==='off')boot();else finish();}if(e.key==='Tab'){const buttons=[...screen.querySelectorAll('button:not([hidden])')];if(buttons.length){e.preventDefault();const i=buttons.indexOf(document.activeElement),next=(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length;buttons[next].focus();}}});}
  function artwork(){const family=V.info().family,id=V.current();if(family==='mac')return '<div class="boot-mac" aria-hidden="true"><span>•‿•</span><i></i></div>';if(family==='linux')return '<div class="boot-linux" aria-hidden="true">'+(id==='kde'?'⚙':'◉')+'</div>';return '<div class="boot-flag" aria-hidden="true"><i></i><i></i><i></i><i></i></div>';}
  function frame(phase,message){createScreen();screen.dataset.phase=phase;screen.innerHTML='<div class="power-stage">'+artwork()+'<div class="boot-brand">'+A.safe(V.info().name)+'</div><div class="boot-edition">'+A.safe(V.info().edition)+'</div><p role="status" aria-live="polite">'+message+'</p><div class="boot-progress" aria-hidden="true"><span></span></div></div><button class="power-skip" type="button">Skip animation</button>';screen.querySelector('.power-skip').addEventListener('click',finish);}
  function closePrograms(){const dialog=document.querySelector('dialog[open]');if(dialog)dialog.close();for(const w of W.list())if(w.state!=='closed')W.close(w.id);try{history.replaceState(null,'',location.pathname+location.search);}catch{}window.TimShell.closeMenu();document.querySelector('#start-menu').hidden=true;document.querySelector('#start-button').setAttribute('aria-expanded','false');}
  function fresh(){try{sessionStorage.removeItem('timbuilds.access-progress.v3');}catch{}W.freshSession();W.close('projects');removeScreen();}
  function poweredOff(){clearTimers();createScreen();screen.dataset.phase='off';screen.innerHTML='<div class="power-message"><p>'+(V.info().family==='mac'?'You may now switch off<br>your Macintosh.':V.info().family==='linux'?'System halted.':'It’s now safe to<br>turn off your computer.')+'</p><div class="power-buttons"><button class="bevel-button" data-power-close>Close tab</button><button class="bevel-button" data-power-start>Start desktop</button></div><small role="status">The web desktop is off. Your device stays on.</small></div>';screen.querySelector('[data-power-start]').addEventListener('click',boot);screen.querySelector('[data-power-close]').addEventListener('click',()=>{window.close();later(()=>{if(screen)screen.querySelector('small').textContent='Your browser kept this tab open. You can close it using the browser’s tab controls.';},200);});screen.querySelector('[data-power-start]').focus({preventScroll:true});}
  function boot(){clearTimers();mode='restart';frame('boot',V.info().family==='mac'?'Welcome to Macintosh.':V.current()==='kde'?'Starting the desktop environment…':V.current()==='ubuntu'?'Starting services…':'Starting '+A.safe(V.info().name)+'…');later(fresh,reduced()?300:3200);}
  function finish(){if(!screen)return;if(screen.dataset.phase==='boot'){fresh();return;}if(mode==='restart')boot();else poweredOff();}
  function start(action){if(screen)return;mode=action==='restart'?'restart':'off';closePrograms();frame('shutdown',V.current()==='xp'?'Saving your settings…':V.info().family==='mac'?'Closing applications…':'Shutting down…');later(()=>{if(mode==='restart')boot();else poweredOff();},reduced()?300:2200);}
  A.register('shutdown','Shut Down','power',body=>{
    body.innerHTML='<div class="accessory-pad"><h2>'+A.safe(V.info().name)+'</h2><p>What would you like to do?</p><label class="shutdown-option"><input type="radio" name="desktop-power" value="off" checked> Shut down</label><label class="shutdown-option"><input type="radio" name="desktop-power" value="restart"> Restart</label><div class="detail-actions"><button class="bevel-button" id="power-ok">OK</button><button class="bevel-button" data-action="close-dialog">Cancel</button></div><p class="accessory-note">This closes your open desktop programs. Save any Paint drawing first. Saved notes, wallpaper choices and owner access are kept.</p></div>';
    body.querySelector('#power-ok').addEventListener('click',()=>start(body.querySelector('input:checked').value));
  });
  window.addEventListener('pagehide',clearTimers);window.TimPower=Object.freeze({start,boot,state:()=>screen?.dataset.phase||'running'});
})();
