/* Voluntary, browser-only screen saver and shutdown screen. */
(() => {
  'use strict';
  const A=window.TimApps;let overlay=null,frame=0,previous=null,inert=[];
  function dismiss(){if(!overlay)return;cancelAnimationFrame(frame);overlay.remove();overlay=null;for(const el of inert)el.inert=false;inert=[];previous?.focus?.({preventScroll:true});}
  function cover(){dismiss();previous=document.activeElement;overlay=document.createElement('div');overlay.className='desktop-cover';overlay.tabIndex=0;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Desktop screen');inert=[...document.body.children].filter(el=>!el.inert&&!['SCRIPT','STYLE'].includes(el.tagName));for(const el of inert)el.inert=true;document.body.append(overlay);overlay.focus();overlay.addEventListener('keydown',e=>{e.preventDefault();e.stopPropagation();dismiss();});return overlay;}
  function stars(){const el=cover(),canvas=document.createElement('canvas'),hint=document.createElement('p');canvas.width=innerWidth;canvas.height=innerHeight;hint.textContent='Move the mouse, tap, or press a key to return.';el.append(canvas,hint);const ctx=canvas.getContext('2d'),points=Array.from({length:120},()=>({x:(Math.random()-.5)*2,y:(Math.random()-.5)*2,z:Math.random()+.05}));let last=performance.now(),started=last;
    function draw(now){if(!overlay||overlay!==el)return;const dt=Math.min(.04,(now-last)/1000);last=now;ctx.fillStyle='black';ctx.fillRect(0,0,canvas.width,canvas.height);for(const p of points){p.z-=dt*.32;if(p.z<.04){p.z=1;p.x=(Math.random()-.5)*2;p.y=(Math.random()-.5)*2;}const x=canvas.width/2+p.x*canvas.width*.4/p.z,y=canvas.height/2+p.y*canvas.height*.4/p.z,r=Math.min(3,1/p.z);ctx.fillStyle='#ffffff';ctx.fillRect(x,y,r,r);}frame=requestAnimationFrame(draw);}
    frame=requestAnimationFrame(draw);el.addEventListener('pointermove',()=>{if(performance.now()-started>600)dismiss();});el.addEventListener('pointerdown',dismiss);
  }
  A.register('screensaver','Screen Saver','computer',body=>{body.innerHTML='<div class="accessory-pad"><h2>Starfield Simulation</h2><div class="saver-preview">✦ &nbsp; · &nbsp; ✧ &nbsp; · &nbsp; ✦</div><p>A starfield screen saver for this desktop.</p><button class="bevel-button" id="saver-preview">Preview</button><p class="accessory-note">Move your pointer or press any key to return. It never locks or changes your real computer.</p></div>';body.querySelector('#saver-preview').addEventListener('click',stars);});
  A.register('shutdown','Shut Down','power',body=>{body.innerHTML='<div class="accessory-pad"><h2>Shut Down</h2><p>What would you like to do?</p><label class="shutdown-option"><input type="radio" name="desktop-power" value="off" checked> Shut down this web desktop</label><label class="shutdown-option"><input type="radio" name="desktop-power" value="restart"> Restart this web desktop</label><div class="detail-actions"><button class="bevel-button" id="power-ok">OK</button><button class="bevel-button" data-action="close-dialog">Cancel</button></div><p class="accessory-note">Your computer stays on. Open program contents are kept until you leave or reload this page.</p></div>';body.querySelector('#power-ok').addEventListener('click',()=>{const restart=body.querySelector('input:checked').value==='restart';window.TimWindows.close('shutdown');if(restart){window.TimWindows.show('projects');return;}const el=cover();el.innerHTML='<div class="power-message"><p>It’s now safe to<br>close this tab.</p><button class="bevel-button">Restart desktop</button></div>';el.querySelector('button').addEventListener('click',dismiss);});});
})();
