/* Each desktop has its own wallpaper catalogue and remembered picture placement. */
(() => {
  'use strict';
  const V=window.TimVersion;
  function preview(el,p){if(!el||!p)return;el.dataset.wallpaperPreview=p.id;for(const name of ['--wall-image','--wall-color','--wall-size','--wall-position'])el.style.removeProperty(name);if(p.file){el.style.setProperty('--wall-image',`url("${new URL("portfolio/wallpapers/"+p.file,document.baseURI).href}")`);el.style.setProperty('--wall-color',V.info().color);el.style.setProperty('--wall-size',el.id==='wallpaper-monitor'?({fit:'contain',fill:'cover',center:'auto',tile:'32% auto'})[V.selection().placement]:'cover');el.style.setProperty('--wall-position','center');el.style.backgroundRepeat=V.selection().placement==='tile'&&el.id==='wallpaper-monitor'?'repeat':'no-repeat';}else{el.style.backgroundRepeat='';if(p.pattern){el.style.setProperty('--wall-color',p.color);el.style.setProperty('--wall-image',p.pattern);el.style.setProperty('--wall-size',p.size);el.style.setProperty('--wall-position','0 0');}else if(p.id==='win2000-blue'){el.style.setProperty('--wall-color','#3a6ea5');el.style.setProperty('--wall-image','none');}}}
  function choices(){const all=V.options();return [['Version wallpapers',all.filter(p=>p.kind!=='creative')],['Extra retro designs',all.filter(p=>p.kind==='creative')]].map(([title,papers])=>`<section class="wallpaper-group"><h3>${title}</h3><div class="wallpaper-options">${papers.map(p=>`<button class="wallpaper-option" data-wallpaper="${p.id}" aria-pressed="${p.id===V.selection().wallpaper}"><span class="wallpaper-swatch" data-wallpaper-preview="${p.id}" aria-hidden="true"></span>${p.label}${p.id.startsWith('mac9-')?'<small>512 Pixels archive / remaster</small>':p.kind==='pattern'?'<small>Re-created desktop pattern</small>':p.kind==='shared'?'<small>Shared classic theme</small>':''}</button>`).join('')}</div></section>`).join('');}
  function sync(){
    const value=V.selection(),papers=V.options(),p=papers.find(p=>p.id===value.wallpaper);
    document.querySelectorAll('.wallpaper-option').forEach(el=>{el.setAttribute('aria-pressed',String(el.dataset.wallpaper===value.wallpaper));preview(el.querySelector('.wallpaper-swatch'),papers.find(p=>p.id===el.dataset.wallpaper));});
    preview(document.querySelector('#wallpaper-monitor'),p);
    const name=document.querySelector('#wallpaper-name');if(name)name.textContent=p.label;
    const placement=document.querySelector('#wallpaper-placement');if(placement)placement.value=value.placement;
    const select=document.querySelector('#display-version-select');if(select)select.value=V.current();
    V.sync();
  }
  function markup(){return `<div class="project-detail-copy display-properties"><div class="eyebrow">DISPLAY PROPERTIES / BACKGROUND</div><label class="display-version-label">Operating system <select id="display-version-select">${V.themes.map(t=>`<option value="${t.id}"${t.id===V.current()?' selected':''}>${t.name}${t.id==='2000'?' (default)':''}</option>`).join('')}</select><button class="bevel-button" data-app-open="versions">Appearance…</button></label><div class="wallpaper-monitor" id="wallpaper-monitor"><div class="mini-window"><span>timBuilds — <b data-os-name>${V.info().name}</b></span><i></i><i></i><i></i></div></div><h2 id="wallpaper-name"></h2><label class="wallpaper-placement">Picture display <select id="wallpaper-placement"><option value="fit">Fit (keep whole image)</option><option value="fill">Fill desktop</option><option value="center">Center (original size)</option><option value="tile">Tile (original size)</option></select></label><p class="accessory-note">The picture collection follows your Operating system. Archived pictures retain their source resolution; extra retro designs are listed separately.</p><div id="wallpaper-catalogue">${choices()}</div><div class="detail-actions"><button class="bevel-button" data-wallpaper-reset>Restore this version’s wallpaper</button><button class="bevel-button" data-action="arrange-icons">Arrange icons on left</button><button class="bevel-button" data-action="reset-window">Reset My Projects</button><button class="bevel-button" data-action="close-dialog">OK</button></div><p class="private-note">Applies immediately. Each version remembers its own wallpaper and placement.</p></div>`;}
  document.addEventListener('change',e=>{if(e.target.id==='wallpaper-placement')V.placement(e.target.value);if(e.target.id==='display-version-select')V.set(e.target.value);});
  document.addEventListener('click',e=>{if(e.target.closest('[data-wallpaper-reset]'))V.reset();});
  window.addEventListener('timbuilds-wallpaper',sync);
  window.addEventListener('timbuilds-version',()=>{const catalogue=document.querySelector('#wallpaper-catalogue');if(catalogue)catalogue.innerHTML=choices();sync();});
  window.TimWallpaper=Object.freeze({get options(){return V.options().map(p=>[p.id,p.label]);},set:id=>V.wallpaper(id),sync,markup});
})();
