import assert from 'node:assert/strict';import path from 'node:path';
export async function checkFinish({evaluate,send,click,box,viewport,navigate,origin,until,sleep,screenshot,output,pass}){
 const open=id=>evaluate('window.TimApps.open('+JSON.stringify(id)+')');
 await viewport(1440,1000);await evaluate('localStorage.removeItem("timbuilds.environment.v1")');await navigate(origin);
 assert.equal(await evaluate('window.TimVersion.current()'),'xp');assert.equal(await evaluate('window.TimVersion.selection().wallpaper'),'winxp-bliss');assert.ok((await evaluate('getComputedStyle(document.querySelector("#desktop-wallpaper")).backgroundImage')).includes('winxp-bliss-hd.jpg'));await screenshot(path.join(output,'xp-default.png'));pass('Fresh desktops use Windows XP with fitted Bliss in metadata, before-paint fallback and actual background');
 await evaluate('window.TimVersion.set("2000");window.TimVersion.wallpaper("win2000-chateau")');await navigate(origin);assert.equal(await evaluate('window.TimVersion.selection().wallpaper'),'win2000-chateau');await evaluate('window.TimVersion.reset()');assert.equal(await evaluate('window.TimVersion.selection().wallpaper'),'win2000-paradise');pass('Custom wallpaper choices survive reload; Reset returns Windows 2000 to Paradise');
 const text=await evaluate('document.body.textContent');for(const phrase of ['personal software, quietly made','No dial-up required.','Built out of curiosity.','Some finished. Some finding their feet.'])assert.ok(!text.includes(phrase),'Removed decorative saying: '+phrase);assert.equal(await evaluate('!!document.querySelector(".desktop-signature")'),false);pass('Decorative slogans and the desktop watermark are removed, without replacing them with more filler');
 const ids=await evaluate('JSON.parse(document.querySelector("#project-data").textContent).map(p=>p.id)');
 for(const width of [390,1440]){
   await viewport(width,900);await evaluate('window.TimWindows.reset("projects");window.TimCatalogue.browse("All projects")');
   for(const view of ['grid','list']){
     await click('[data-view="'+view+'"]');
     const images=await evaluate('[...document.querySelectorAll(".project-card:not([hidden]) .card-preview>img")].map(i=>{const r=i.getBoundingClientRect();return {ratio:r.width/r.height,fit:getComputedStyle(i).objectFit,src:i.getAttribute("src")};})');assert.equal(images.length,13);assert.ok(images.every(i=>Math.abs(i.ratio-12/7)<.015&&i.fit==='contain'));await screenshot(path.join(output,'previews-'+width+'-'+view+'.png'));
   }
 }
 await click('[data-view=grid]');for(const id of ['solitaire','letters-with-lola','block-app','tv-app']){await click('.project-card[data-id="'+id+'"] [data-project]');await until(()=>evaluate('document.querySelector(".project-detail-preview").complete&&document.querySelector(".project-detail-preview").naturalWidth===1200'),'preview image');const dims=await evaluate('(()=>{const i=document.querySelector(".project-detail-preview"),r=i.getBoundingClientRect();return {ratio:r.width/r.height,fit:getComputedStyle(i).objectFit};})()');assert.ok(Math.abs(dims.ratio-12/7)<.015&&dims.fit==='contain');await click('.dialog-close');}
 pass('All thirteen previews retain full aspect ratio in desktop/mobile card and list views; replaced captures fit project details');
 for(const os of ['95','98','2000','xp','system7','mac9','ubuntu','kde'])for(const width of [390,1440]){
   await viewport(width,900);await evaluate('window.TimVersion.set('+JSON.stringify(os)+');window.TimWindows.showDesktop()');await open('notepad');await evaluate('window.TimWindows.reset("notepad")');
   const controls=await evaluate('(()=>{const w=document.querySelector("#window-notepad"),t=w.querySelector(".titlebar").getBoundingClientRect();return [...w.querySelectorAll(".window-controls>button")].map(b=>{const r=b.getBoundingClientRect(),s=b.querySelector("svg");return {hitTarget:String(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.className),hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest("button")===b,kind:b.dataset.chromeIcon,label:b.getAttribute("aria-label"),svg:!!s,path:!!s?.querySelector("path"),x:r.x,y:r.y,w:r.width,h:r.height,inside:r.left>=t.left-1&&r.right<=t.right+1&&r.top>=t.top-1&&r.bottom<=t.bottom+1};});})()');assert.deepEqual(controls.map(c=>c.kind),['minimize','maximize','close']);assert.ok(controls.every(c=>c.hit&&c.svg&&c.path&&c.label&&c.w>=15&&c.h>=15&&c.inside),os+' controls fit '+width+' '+JSON.stringify(controls));
   for(let i=0;i<controls.length;i++)for(let j=i+1;j<controls.length;j++){const a=controls[i],b=controls[j];assert.ok(a.x+a.w<=b.x+.5||b.x+b.w<=a.x+.5,'Controls do not overlap');}
   await click('#window-notepad [data-win-control=maximize]');assert.equal(await evaluate('document.querySelector("#window-notepad [data-win-control=maximize]").dataset.chromeIcon'),'restore');await click('#window-notepad [data-win-control=maximize]');assert.equal(await evaluate('document.querySelector("#window-notepad [data-win-control=maximize]").dataset.chromeIcon'),'maximize');await screenshot(path.join(output,'finished-chrome-'+os+'-'+width+'.png'));await click('#window-notepad [data-win-control=close]');
 }
 pass('Vector minimise/maximise/restore/close controls are aligned, labelled, non-overlapping and functional in all eight skins on desktop and phone');
 await viewport(390,844);await evaluate('window.TimVersion.set("2000");window.TimDesktopActions.warn("move")');assert.equal(await evaluate('document.querySelector("#bsod-stop").textContent'),'PROJECTS_CANNOT_BE_RECYCLED');const r=await box('#bsod-dialog');assert.ok(r.w===390&&r.h===844);await screenshot(path.join(output,'nice-try-mobile.png'));await click('#bsod-dialog [data-bsod-action="desktop"]');
 pass('Protected-project Stop screen fills the phone with an always-available desktop return control');
 await viewport(1440,1000);await navigate(origin);await evaluate('window.TimVersion.set("2000");window.TimVersion.reset();window.TimWindows.reset("projects");window.TimDesktop.arrange()');
}
