import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';
export async function checkClassic({evaluate,send,click,box,mouse,drag,viewport,navigate,origin,until,sleep,screenshot,output,pass,requests}) {
 const open=id=>evaluate(`window.TimApps.open(${JSON.stringify(id)})`);
 const close=id=>evaluate(`window.TimWindows.close(${JSON.stringify(id)})`);
 const key=async (name,code=name)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:name,code});await send('Input.dispatchKeyEvent',{type:'keyUp',key:name,code});};
 await viewport(1440,1000);await navigate(origin);await evaluate('window.TimWindows.showDesktop()');
 async function right(x,y){await send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'right',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'right',clickCount:1});}
 await right(1350,850);assert.equal(await evaluate('document.querySelector("#desktop-context-menu").hidden'),false);const menu=await box('#desktop-context-menu');assert.ok(menu.x+menu.w<=1440&&menu.y+menu.h<=1000);await screenshot(path.join(output,'desktop-context.png'));await key('Escape');assert.equal(await evaluate('document.querySelector("#desktop-context-menu").hidden'),true);pass('Real right-click opens a bounded desktop menu; Escape dismisses it');
 await click('.clock-tray');assert.equal(await evaluate('document.querySelector("#window-datetime").hidden'),false);const month=await evaluate('document.querySelector("#calendar-month").textContent');await click('[data-month="1"]');assert.notEqual(await evaluate('document.querySelector("#calendar-month").textContent'),month);await click('#calendar-today');assert.equal(await evaluate('document.querySelector("#calendar-month").textContent'),month);assert.ok((await evaluate('document.querySelector("#live-time").textContent')).length>4);await screenshot(path.join(output,'clock-calendar.png'));await close('datetime');pass('Clock opens an independent live clock/calendar with month navigation and Today');
 await click('#start-button');await click('.start-parent');assert.equal(await evaluate('document.querySelector(".start-parent").getAttribute("aria-expanded")'),'true');await click('#start-menu [data-app-open="calculator"]');assert.equal(await evaluate('document.querySelector("#start-menu").hidden'),true);assert.equal(await evaluate('window.TimWindows.active()'),'calculator');
 for(const value of ['2','+','3','='])await click(`[data-calc="${value}"]`);assert.equal(await evaluate('document.querySelector("#calculator-display").textContent'),'5');await key('Escape');assert.equal(await evaluate('document.querySelector("#window-calculator").hidden'),false);assert.equal(await evaluate('document.querySelector("#calculator-display").textContent'),'0');await close('calculator');pass('Start submenu launches Calculator; arithmetic works and Escape clears rather than closing it');
 await open('run');await evaluate('document.querySelector("#run-command").value="calc.exe";document.querySelector("#run-form").requestSubmit()');assert.equal(await evaluate('window.TimWindows.active()'),'calculator');await close('calculator');await open('run');await evaluate('document.querySelector("#run-command").value="not-a-program";document.querySelector("#run-form").requestSubmit()');assert.ok((await evaluate('document.querySelector("#run-status").textContent')).includes('Cannot find'));await close('run');pass('Run launches allowlisted accessory names and rejects unknown commands');
 await open('notepad');await evaluate('document.querySelector("#notepad-text").value="A test note, not a user file.";document.querySelector("#notepad-text").dispatchEvent(new Event("input"))');await close('notepad');await open('notepad');assert.equal(await evaluate('document.querySelector("#notepad-text").value'),'A test note, not a user file.');await click('#window-notepad [data-command="recycle"]');assert.equal(await evaluate('document.querySelector("#notepad-text").value'),'');await close('notepad');await open('recycle');assert.equal(await evaluate('document.querySelectorAll("[data-restore]").length'),1);await click('[data-restore]');assert.equal(await evaluate('document.querySelector("#notepad-text").value'),'A test note, not a user file.');await close('notepad');await close('recycle');pass('Notepad persists locally; browser Recycle Bin restores a deleted note');
 await open('paint');const canvas=await box('#paint-canvas');const beforePaint=await evaluate('document.querySelector("#paint-canvas").toDataURL()');await mouse(canvas.x+canvas.w*.2,canvas.y+canvas.h*.2,'mousePressed');await mouse(canvas.x+canvas.w*.6,canvas.y+canvas.h*.5);await mouse(canvas.x+canvas.w*.6,canvas.y+canvas.h*.5,'mouseReleased');assert.notEqual(await evaluate('document.querySelector("#paint-canvas").toDataURL()'),beforePaint);await evaluate('[...document.querySelectorAll("#window-paint button")].find(b=>b.textContent==="Undo").click()');assert.equal(await evaluate('document.querySelector("#paint-canvas").toDataURL()'),beforePaint);await close('paint');pass('Real pointer input draws on Paint; Undo restores the untouched canvas');
 await open('minesweeper');await click('[data-cell="0"]');assert.equal(await evaluate('document.querySelector("#mine-new").textContent'),'☺');const covered=await evaluate('[...document.querySelectorAll(".mine-cell")].find(b=>!b.classList.contains("revealed")).dataset.cell');const c=await box(`[data-cell="${covered}"]`);await right(c.x+c.w/2,c.y+c.h/2);assert.equal(await evaluate(`document.querySelector('[data-cell="${covered}"]').textContent`),'⚑');assert.equal(await evaluate('document.querySelector("#desktop-context-menu").hidden'),true);await screenshot(path.join(output,'minesweeper.png'));await close('minesweeper');pass('Minesweeper has a safe first click and game-specific right-click flagging');
 await open('notepad');await open('calculator');await evaluate('window.TimWindows.showDesktop()');assert.equal(await evaluate('window.TimWindows.list().filter(w=>w.state==="open").length'),0);await evaluate('window.TimWindows.restoreDesktop()');assert.ok(await evaluate('window.TimWindows.list().filter(w=>w.state==="open").length>=2'));await evaluate('window.TimWindows.arrange("cascade")');for(const id of ['notepad','calculator']){const r=await box('#window-'+id);assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=1440&&r.y+r.h<=1000);}await close('notepad');await close('calculator');pass('Show Desktop, restore and cascade preserve open application state');
 for(const id of ['notepad','calculator','paint','datetime','minesweeper','computer','settings','run'])await open(id);await evaluate('window.TimWindows.arrange("vertical")');const boxes=await evaluate("[...document.querySelectorAll(\"[data-window-id]:not([hidden])\")].map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};})");for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(a.x+a.w<=b.x+.5||b.x+b.w<=a.x+.5||a.y+a.h<=b.y+.5||b.y+b.h<=a.y+.5,'Tiled windows do not overlap');}const tile=await box('#window-notepad');await evaluate('window.TimWindows.maximize("notepad");window.TimWindows.maximize("notepad")');assert.deepEqual(await box('#window-notepad'),tile);for(const id of ['notepad','calculator','paint','datetime','minesweeper','computer','settings','run'])await close(id);pass('Eight tiled windows do not overlap; maximise/restore retains their tile geometry');
 await open('screensaver');await click('#saver-preview');assert.equal(await evaluate('document.querySelectorAll(".desktop-cover").length'),1);await key('Escape');assert.equal(await evaluate('document.querySelectorAll(".desktop-cover").length'),0);assert.equal(await evaluate('document.querySelector("#window-screensaver").inert'),false);await close('screensaver');await open('shutdown');await click('#power-ok');assert.equal(await evaluate('document.querySelectorAll(".desktop-cover").length'),1);await click('.power-skip');await click('[data-power-start]');await click('.power-skip');assert.equal(await evaluate('document.querySelectorAll(".desktop-cover").length'),0);await evaluate('window.TimWindows.show("projects")');pass('Screen saver and web-only shutdown screen exit cleanly and restore keyboard access');
 await evaluate('window.TimVersion.set("95")'); await evaluate('document.querySelector(".desktop-shortcut[data-dialog=display]").click()');const originalIds=await evaluate('window.TimWallpaper.options.filter(o=>o[0].startsWith("win95-")).map(o=>o[0])');assert.equal(originalIds.length,12);for(const id of originalIds){assert.equal(await evaluate(`new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image.naturalWidth>=600&&image.naturalHeight>=400);image.onerror=()=>resolve(false);image.src='portfolio/wallpapers/${id}.jpg';})`),true,id+' loads at archival resolution');}await click('[data-wallpaper="win95-wi"]');await evaluate('document.querySelector("#wallpaper-placement").value="fill";document.querySelector("#wallpaper-placement").dispatchEvent(new Event("change",{bubbles:true}))');assert.equal(await evaluate('getComputedStyle(document.body).backgroundSize'),'cover');await screenshot(path.join(output,'original-wallpapers.png'));await close('display');pass('Twelve original Windows 95 Plus! archive images load, with Fill/Center/Tile/Fit placement');
 await open('pinball');await until(()=>evaluate('document.querySelector("#window-pinball").dataset.pinballReady==="true"'),'pinball runtime');await sleep(1500);
 const frameBox=await box('#pinball-frame');const capture=await send('Page.captureScreenshot',{format:'png',clip:{x:frameBox.x,y:frameBox.y,width:frameBox.w,height:frameBox.h,scale:1}});fs.writeFileSync(path.join(output,'pinball-table.png'),Buffer.from(capture.data,'base64'));
 const colors=await evaluate(`new Promise(resolve=>{const image=new Image();image.onload=()=>{const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d');x.drawImage(image,0,0);const d=x.getImageData(0,0,c.width,c.height).data,colors=new Set();for(let i=0;i<d.length;i+=32)colors.add(d[i]+','+d[i+1]+','+d[i+2]);resolve(colors.size);};image.src='data:image/png;base64,${capture.data}';})`);assert.ok(colors>150,'Pinball draws a detailed table, not a blank loading canvas');
 const left=await box('[data-pin-key="left"]');await mouse(left.x+left.w/2,left.y+left.h/2,'mousePressed');await sleep(400);await screenshot(path.join(output,'pinball-left-flipper.png'));await mouse(left.x+left.w/2,left.y+left.h/2,'mouseReleased');
 await click('[data-pin-action="new"]');const launch=await box('[data-pin-key="launch"]');await mouse(launch.x+launch.w/2,launch.y+launch.h/2,'mousePressed');await sleep(1600);await screenshot(path.join(output,'pinball-plunger-held.png'));await mouse(launch.x+launch.w/2,launch.y+launch.h/2,'mouseReleased');await sleep(400);await screenshot(path.join(output,'pinball-playing.png'));
 await evaluate('window.__retainedPinball=document.querySelector("#pinball-frame").contentWindow;true');for(const version of ['98','2000','xp','95']){await evaluate('window.TimVersion.set('+JSON.stringify(version)+')');assert.equal(await evaluate('document.querySelector("#pinball-frame").contentWindow===window.__retainedPinball'),true);}pass('Version switching preserves the running pinball instance without reloading its assets');
 await close('display');await evaluate('window.TimWindows.minimize("pinball")');await sleep(250);assert.equal(await evaluate('document.querySelector("#pinball-frame").contentDocument.documentElement.dataset.paused'),'true');await evaluate('window.TimWindows.show("pinball")');await sleep(150);assert.equal(await evaluate('document.querySelector("#pinball-frame").contentDocument.documentElement.dataset.paused'),'false');await close('pinball');assert.equal(await evaluate('document.querySelectorAll("#pinball-frame").length'),0);pass('Self-hosted pinball renders a detailed table, accepts launch controls, pauses on minimise and unloads on close');
 const external=requests.filter(url=>/^https?:/.test(url)&&new URL(url).origin!==new URL(origin).origin);assert.deepEqual(external,[],'Accessories and games use no external runtime services');pass('Wallpapers, pinball and accessories run without third-party requests or trackers');
 for(const width of [320,390,768]){await viewport(width,844);for(const id of ['datetime','calculator','notepad','paint','minesweeper','computer','run']){await open(id);const r=await box('#window-'+id);assert.ok(r.x>=0&&r.x+r.w<=width,id+' is in bounds');const overflow=await evaluate(`(()=>{const el=document.querySelector('#window-${id} .app-window-body');return el.scrollWidth>el.clientWidth+1;})()`);assert.equal(overflow,false,id+' fits at '+width);if(width===390&&id==='datetime')await screenshot(path.join(output,'calendar-mobile.png'));await close(id);}}
 pass('Seven accessories fit 320–768 px layouts without horizontal overflow');
 await viewport(1440,1000);await navigate(origin);await evaluate('window.TimWallpaper.set("win95-wi");window.TimWindows.showDesktop()');await open('datetime');await open('minesweeper');await open('notepad');await screenshot(path.join(output,'classic-desktop.png'));
 for(const id of ['datetime','minesweeper','notepad'])await close(id);await evaluate('window.TimWallpaper.set("teal");window.TimWindows.show("projects")');
}
