import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const context={};vm.runInNewContext(fs.readFileSync(new URL('../portfolio/arcade-engines.js',import.meta.url),'utf8'),context);const {Solitaire,Reversi,Golf,courses}=context.TimArcadeEngines;
for(let seed=1;seed<=100;seed++){let state=seed;const random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};const g=new Solitaire(random),all=[...g.stock,...g.tableau.flat()];assert.equal(new Set(all.map(c=>c.id)).size,52);assert.equal(g.stock.length,24);assert.equal(g.tableau.filter(p=>p.at(-1).up).length,7);const original=JSON.stringify(g.snapshot());g.draw();assert.equal(g.waste.length,1);g.undo();assert.equal(JSON.stringify(g.snapshot()),original);for(let i=0;i<24;i++)g.draw();assert.equal(g.stock.length,0);g.draw();assert.equal(g.stock.length,24);assert.equal(g.waste.length,0);}
const s=new Solitaire();s.tableau=[[],[],[],[],[],[],[]];s.stock=[];s.waste=[{id:0,suit:0,rank:1,up:true}];assert.ok(s.move({type:'waste',pile:0},{type:'foundation',pile:0}));assert.equal(s.foundations[0].length,1);assert.ok(s.undo());assert.equal(s.waste.length,1);s.tableau[0]=[{id:12,suit:0,rank:13,up:true}];s.waste=[{id:24,suit:1,rank:12,up:true}];assert.ok(s.move({type:'waste',pile:0},{type:'tableau',pile:0}));assert.equal(s.tableau[0].length,2);assert.equal(s.move({type:'tableau',pile:0,index:1},{type:'tableau',pile:2}),false);assert.ok(s.move({type:'tableau',pile:0,index:0},{type:'tableau',pile:2}));
for(let trial=0;trial<100;trial++){const r=new Reversi();assert.equal(r.legal().length,4);let count=0;while(!r.over&&count++<70){const legal=r.legal();assert.ok(legal.length>0);const n=legal[(count+trial)%legal.length],before=r.board.filter(Boolean).length;assert.ok(r.move(n));assert.equal(r.board.filter(Boolean).length,before+1);}assert.ok(r.over);assert.ok(count<=60);assert.ok(r.undo());assert.equal(r.over,false);}
for(let index=0;index<courses.length;index++){const g=new Golf(index),c=courses[index];for(let angle=0;angle<360;angle+=30){const test=new Golf(index);test.shoot(angle*Math.PI/180,70);for(let n=0;n<1600&&test.moving;n++)test.step();assert.ok(Number.isFinite(test.x)&&Number.isFinite(test.y));assert.ok(test.x>=20&&test.x<=700&&test.y>=20&&test.y<=400);}
 const blocked=(x,y)=>x<30||x>690||y<30||y>390||[...c.walls,...c.water].some(r=>x>=r[0]-8&&x<=r[0]+r[2]+8&&y>=r[1]-8&&y<=r[1]+r[3]+8);const start=c.start.map(n=>Math.round(n/10)*10),queue=[start],seen=new Set([start.join(',')]);let reached=false;
 while(queue.length){const [x,y]=queue.shift();if(Math.hypot(x-c.cup[0],y-c.cup[1])<16){reached=true;break;}for(const [dx,dy] of [[10,0],[-10,0],[0,10],[0,-10]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(!seen.has(k)&&!blocked(nx,ny)){seen.add(k);queue.push([nx,ny]);}}}assert.ok(reached,'Reachable cup: '+c.name);
}
const putt=new Golf();assert.ok(putt.shoot(0,46));assert.equal(putt.shoot(0,46),false);for(let n=0;n<1500&&putt.moving;n++)putt.step();assert.ok(putt.sunk,'First hole can be completed');
console.log('PASS: 100 Solitaire deals and move/undo rules; 100 complete Reversi games; all nine golf courses reachable, 108 shot simulations and a successful first-hole putt.');
